### PR TITLE
Create TRC issue template

### PR DESCRIPTION
**Pull request by jpstroop**

### CODE REVIEW

**Comment by jpstroop** [comment]
I don't know the rules for merging here but I assume that at some point someone will pull the trigger.

**Comment by azaroth42** [comment]
Propose that the first three headings can be merged into a single section with bullets.
Also that a Background section has been useful for getting people up to speed.

**Comment by jpstroop** [comment]
@IIIF/iiif-staff ?

**Comment by hadro** [comment]
Is the question about merging, or @azaroth42's suggestions?
I'm happy to merge if that's what y'all are waiting on.

**Comment by jpstroop** [comment]
Oh, I guess I needed to refresh my page. Hadn't seen @azaroth42's comment. Will push up changes momentarily.

**Comment by jpstroop** [comment]
OK, @IIIF/iiif-staff @IIIF/editors ....

**Pull request merged**
